services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    #Below makes the REDIS_HOST as used in the settings.py file as specified
    #by the redis services defined in this file.
    #it overrides the value specified in the settings.py.
    environment:
      - REDIS_HOST=redis 
    ports:
      - '8000:8000'
    links:
      - redis